// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID            uuid.UUID
	Email         string
	Moniker       sql.NullString
	PasswordHash  string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	AccountActive bool
}

type UserEncryption struct {
	UserID                uuid.UUID
	PasswordSalt          string
	PasswordParams        json.RawMessage
	EncryptedMasterKeyPw  string
	RecoverySalt          string
	RecoveryParams        json.RawMessage
	EncryptedMasterKeyRec string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}
