// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID    uuid.UUID
	Email string
}

type Experience struct {
	ID             uuid.UUID
	Date           time.Time
	FrontendDate   string
	CompanyName    string
	Role           string
	Tags           []string
	Description    string
	CompanyWebsite string
}
