// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package models

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email,moniker,password_hash
) VALUES (
  $1,$2,$3
)
RETURNING id, email, moniker, password_hash, created_at, updated_at, account_active
`

type CreateUserParams struct {
	Email        string
	Moniker      sql.NullString
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Moniker, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Moniker,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountActive,
	)
	return i, err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users WHERE id=$1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserByID, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, moniker, password_hash, created_at, updated_at, account_active FROM users WHERE email=$1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Moniker,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountActive,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, moniker, password_hash, created_at, updated_at, account_active FROM users WHERE id=$1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Moniker,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountActive,
	)
	return i, err
}
