// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_encryption.sql

package models

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createEncryption = `-- name: CreateEncryption :one
INSERT INTO user_encryption(
    user_id, password_salt, password_params, encrypted_master_key_pw, recovery_salt, recovery_params, encrypted_master_key_rec
) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING user_id, password_salt, password_params, encrypted_master_key_pw, recovery_salt, recovery_params, encrypted_master_key_rec, created_at, updated_at
`

type CreateEncryptionParams struct {
	UserID                uuid.UUID
	PasswordSalt          string
	PasswordParams        json.RawMessage
	EncryptedMasterKeyPw  string
	RecoverySalt          string
	RecoveryParams        json.RawMessage
	EncryptedMasterKeyRec string
}

func (q *Queries) CreateEncryption(ctx context.Context, arg CreateEncryptionParams) (UserEncryption, error) {
	row := q.db.QueryRowContext(ctx, createEncryption,
		arg.UserID,
		arg.PasswordSalt,
		arg.PasswordParams,
		arg.EncryptedMasterKeyPw,
		arg.RecoverySalt,
		arg.RecoveryParams,
		arg.EncryptedMasterKeyRec,
	)
	var i UserEncryption
	err := row.Scan(
		&i.UserID,
		&i.PasswordSalt,
		&i.PasswordParams,
		&i.EncryptedMasterKeyPw,
		&i.RecoverySalt,
		&i.RecoveryParams,
		&i.EncryptedMasterKeyRec,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
