// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_encryption.sql

package models

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createEncryption = `-- name: CreateEncryption :one
INSERT INTO user_encryption(
    user_id, password_salt, password_params, encrypted_master_key_pw, recovery_salt, recovery_params, encrypted_master_key_rec, recovery_hash
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING user_id, password_salt, password_params, encrypted_master_key_pw, recovery_salt, recovery_params, encrypted_master_key_rec, recovery_hash, created_at, updated_at
`

type CreateEncryptionParams struct {
	UserID                uuid.UUID
	PasswordSalt          string
	PasswordParams        json.RawMessage
	EncryptedMasterKeyPw  string
	RecoverySalt          string
	RecoveryParams        json.RawMessage
	EncryptedMasterKeyRec string
	RecoveryHash          string
}

func (q *Queries) CreateEncryption(ctx context.Context, arg CreateEncryptionParams) (UserEncryption, error) {
	row := q.db.QueryRowContext(ctx, createEncryption,
		arg.UserID,
		arg.PasswordSalt,
		arg.PasswordParams,
		arg.EncryptedMasterKeyPw,
		arg.RecoverySalt,
		arg.RecoveryParams,
		arg.EncryptedMasterKeyRec,
		arg.RecoveryHash,
	)
	var i UserEncryption
	err := row.Scan(
		&i.UserID,
		&i.PasswordSalt,
		&i.PasswordParams,
		&i.EncryptedMasterKeyPw,
		&i.RecoverySalt,
		&i.RecoveryParams,
		&i.EncryptedMasterKeyRec,
		&i.RecoveryHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEncryptionByUserID = `-- name: GetEncryptionByUserID :one
SELECT user_id, password_salt, password_params, encrypted_master_key_pw, recovery_salt, recovery_params, encrypted_master_key_rec, recovery_hash, created_at, updated_at FROM user_encryption WHERE user_id = $1
`

func (q *Queries) GetEncryptionByUserID(ctx context.Context, userID uuid.UUID) (UserEncryption, error) {
	row := q.db.QueryRowContext(ctx, getEncryptionByUserID, userID)
	var i UserEncryption
	err := row.Scan(
		&i.UserID,
		&i.PasswordSalt,
		&i.PasswordParams,
		&i.EncryptedMasterKeyPw,
		&i.RecoverySalt,
		&i.RecoveryParams,
		&i.EncryptedMasterKeyRec,
		&i.RecoveryHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEncryption = `-- name: UpdateEncryption :exec
UPDATE user_encryption SET
    password_salt = $2,
    password_params = $3,
    encrypted_master_key_pw = $4,
    updated_at = now()
WHERE user_id = $1
`

type UpdateEncryptionParams struct {
	UserID               uuid.UUID
	PasswordSalt         string
	PasswordParams       json.RawMessage
	EncryptedMasterKeyPw string
}

func (q *Queries) UpdateEncryption(ctx context.Context, arg UpdateEncryptionParams) error {
	_, err := q.db.ExecContext(ctx, updateEncryption,
		arg.UserID,
		arg.PasswordSalt,
		arg.PasswordParams,
		arg.EncryptedMasterKeyPw,
	)
	return err
}
