// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package models

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO accounts (
  email
) VALUES (
  $1
)
RETURNING id, email
`

func (q *Queries) CreateUser(ctx context.Context, email string) (Account, error) {
	row := q.db.QueryRowContext(ctx, createUser, email)
	var i Account
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}
